name: Generate APK and AAB (Upload as Artifacts)

env:
  # Replace this with your app's module name if not 'app'
  main_project_module: app

  # The name of the Play Store app
  playstore_name: IIECat

on:
  # Triggers on push to any branch
  push:
    branches:
      - '**'
  # Allows manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew build

      - name: Build APK (Debug)
        run: ./gradlew ${{ env.main_project_module }}:assembleDebug

      - name: Build APK (Release)
        run: ./gradlew ${{ env.main_project_module }}:assembleRelease

      - name: Build AAB (Release)
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK Debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK Release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - AAB Release
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
